#main.yml
name: learn-github-actions  #이름 상관없음
on:
  push:
    branches: #main 브랜치에 푸시 될때마다
      - main 

defaults:
  run:
    working-directory: /home/jacob/test_runner_work

jobs:
  self-runner-testing: #이름 상관없음
    runs-on: self-hosted
    steps:

      - name: Configure Git
        uses: actions/checkout@v3
        with:
          repository: parkj12b/test_runner
          ref: main
          token: ${{ secrets.TOKEN }}

      - name: echo hw
        run: echo "hello world" >> hello.txt

